# Generated by Django 4.2.2 on 2023-06-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
