# Generated by Django 4.2.2 on 2023-06-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
